language: elixir

cache:
  directories:
    - ~/.hex
    - ~/.mix
    - _build


matrix:
  include:
    - otp_release: 21.3
      elixir: 1.8
    - otp_release: 21.3
      elixir: 1.7
    - otp_release: 20.3
      elixir: 1.6
    - otp_release: 19.3
      elixir: 1.5
      env: SKIP_FORMAT_CHECK=true
    - otp_release: 18.3
      elixir: 1.4
      env: SKIP_FORMAT_CHECK=true

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - if [ -z "$SKIP_FORMAT_CHECK" ]; then mix format --check-formatted; fi
  - mix credo
  - mix test
  - MIX_ENV=test mix dialyzer --halt-exit-status

# Leave only the .plt files in build
before_cache:
  - mix deps.clean --all --build
  - mix clean --build